import { mkdir, writeFile } from 'node:fs/promises';
(globalThis as any).localStorage = { getItem: () => null, setItem: () => undefined, removeItem: () => undefined, clear: () => undefined };
process.on('unhandledRejection', (reason) => { console.error('UNHANDLED_REJECTION_DETAIL'); try { console.error(JSON.stringify(reason, null, 2)); } catch { console.error(reason); } process.exitCode = 1; });

type Scope = 'Coverall' | 'Vix' | 'All';
const OUT_DIR = 'C:/Users/jasfi/OneDrive/Desktop/Documents/Claude/Projects/commission recon/ambetter-reconcile-hub/tmp-v8-post-sync-rerun';
const V8_TIME = '2026-05-26T22:24:41Z';
const months = ['2026-01', '2026-02', '2026-03', '2026-04'];

const [persistence, resolved, mt, cls, picker, mergeMod, agents, constants, activeBo, boundsMod, dateRange, edeQ, expectedEde, runtimeBo, metrics, supabaseClient] = await Promise.all([
  import('@/lib/persistence'),
  import('@/lib/resolvedIdentities'),
  import('@/lib/memberTimeline'),
  import('@/lib/classifier'),
  import('@/lib/canonical/edeMonthPicker'),
  import('@/lib/canonical/memberKeyMerge'),
  import('@/lib/agents'),
  import('@/lib/constants'),
  import('@/lib/canonical/isActiveBackOfficeRecord'),
  import('@/lib/canonical/statementMonthBounds'),
  import('@/lib/dateRange'),
  import('@/lib/canonical/edeQualified'),
  import('@/lib/expectedEde'),
  import('@/lib/canonical/applyRuntimeBOActive'),
  import('@/lib/canonical/metrics'),
  import('@/integrations/supabase/client'),
]);

const { getBatches, getAllNormalizedRecordsForMemberTimeline, getNormalizedRecords, getReconciledMembers } = persistence;
const { loadResolverIndex } = resolved;
const { buildMemberTimeline, buildMonthList, applyNoSourceInvariantToMonthCell } = mt;
const { buildClassifierContext, buildIsDueEligibleRecord, classifyMember, computeFirstEligibleMonth, classifyMemberForMonth, netPremiumForServiceMonth, paidForServiceMonth } = cls;
const { buildMonthPickerMapForMember, pickEdeForServiceMonth } = picker;
const { mergeRecordsToMemberKeys } = mergeMod;
const { isCoverallAORByName } = agents;
const { NPN_MAP } = constants;
const { isActiveBackOfficeRecord } = activeBo;
const { getStatementMonthBounds } = boundsMod;
const { monthKeyToFirstOfMonth, getCoveredMonths } = dateRange;
const { isEDEQualified } = edeQ;
const { computeFilteredEde } = expectedEde;
const { applyRuntimeBOActive } = runtimeBo;
const { getExpectedPaymentBreakdown } = metrics;
const { supabase } = supabaseClient;

function ym(v:any){ const s=String(v??'').trim(); const m=s.match(/^(\d{4})-(\d{2})/); return m?m[1]+'-'+m[2]:''; }
function fam(x:any){ const raw=typeof x==='string'?x:(x?.carrier ?? x?.raw_json?.issuer ?? ''); return String(raw).toLowerCase().includes('ambetter')?'Ambetter':String(raw??'').trim(); }
function cp(r:any){ return String(r?.raw_json?.currentPolicyAOR ?? r?.raw_json?.['currentPolicyAOR'] ?? '').trim(); }
function bn(r:any){ return String(r?.raw_json?.['Broker Name'] ?? r?.raw_json?.broker_name ?? '').trim(); }
function clone(recs:any[]){ return recs.map(r=>({ ...r, raw_json:{ ...(r.raw_json??{}) } })); }
function group(recs:any[]){ const m=new Map<string,any[]>(); for(const r of recs){ const k=r.member_key||r.applicant_name||'unknown'; const a=m.get(k)||[]; a.push(r); m.set(k,a); } return m; }
function rawMap(recs:any[]){ return group(recs); }
function key(mk:string,m:string){ return mk+'|'+m; }
function compactRow(r:any){ if(!r) return null; return { id:r.id, member_key:r.member_key, name:r.applicant_name, policy_number:r.policy_number, source_type:r.source_type, source_file_label:r.source_file_label, currentPolicyAOR:cp(r), broker_name:bn(r), agent_npn:r.agent_npn, agent_name:r.agent_name, aor_bucket:r.aor_bucket, pay_entity:r.pay_entity, effective_date:r.effective_date, broker_effective_date:r.broker_effective_date, policy_term_date:r.policy_term_date, broker_term_date:r.broker_term_date, paid_through_date:r.paid_through_date, eligible_for_commission:r.eligible_for_commission, net_premium:r.net_premium, member_responsibility:r.member_responsibility }; }
function compactCell(row:any, month:string){ const c=row?.cells?.[month]??{}; return { member_key:row?.member_key, name:row?.applicant_name, policy_number:row?.policy_number, service_month:month, state:c.state??null, reason:c.state_reason??null, in_ede:!!c.in_ede, in_back_office:!!c.in_back_office, in_commission:!!c.in_commission, due:!!c.due, paid_amount:Number(c.paid_amount??0), carrier_recognition:!!c.carrier_recognition, carrier_recognition_premium:c.carrier_recognition_premium??null, netBucket:c.netBucket??null }; }
function counts(rows:any[], prop:string){ const out:any={}; for(const r of rows){ const k=String(r[prop]??''); out[k]=(out[k]??0)+1; } return out; }
function sample<T>(a:T[], n=5){ return a.slice(0,n); }

function legacyPred(payEntity:Scope){ return (r:any) => { const isC=r?.source_type==='COMMISSION'; if(!isC){ const ok=isCoverallAORByName(r?.aor_bucket)||isCoverallAORByName(cp(r))||isCoverallAORByName(bn(r)); if(!ok) return false; } if(payEntity!=='All'){ if(isC){ if(String(r?.pay_entity||'').trim()!==payEntity) return false; } else { const info=(NPN_MAP as any)[String(r?.agent_npn||'').trim()]; if(!info) return false; if(info.expectedPayEntity!==payEntity && info.expectedPayEntity!=='Coverall_or_Vix') return false; } } return true; } }

function buildScreen(source:any[], resolverIndex:any, payEntity:Scope, mode:'current'|'legacy', monthList:string[], batchMonthByBatchId:Map<string,string>){
  const recs=clone(source); mergeRecordsToMemberKeys(recs as any, resolverIndex);
  const pred = mode==='current' ? buildIsDueEligibleRecord({aorScope:'official', payEntity}) : legacyPred(payEntity);
  const rawBy=rawMap(recs); const pickerMaps=new Map<string,Map<string,any|null>>();
  if(mode==='current') for(const [mk,rs] of rawBy) pickerMaps.set(mk, buildMonthPickerMapForMember(rs, monthList));
  const rows0=buildMemberTimeline(recs as any, monthList, pred, mode==='current'?{rawRecordsByMemberKey:rawBy, pickerMapsByMemberKey:pickerMaps, selectedAorScope:'official', payEntity}:undefined);
  const scoped=recs.filter(pred); const by=group(scoped); const base=buildClassifierContext(scoped as any, monthList, [], {batchMonthByBatchId});
  const rows=rows0.map((row:any)=>{ const rs=by.get(row.member_key)||[]; if(!rs.length) return row; const pm=mode==='current'?pickerMaps.get(row.member_key):undefined; const ctx=mode==='current'?{...base,pickerEdeByMonth:pm}:base; const cl=classifyMember(rs as any, ctx as any); const cells={...row.cells}; let months_paid=0, months_unpaid=0, months_due=0; for(const m of monthList){ const cc=cl.cells[m], ex=cells[m]; if(!cc||!ex) continue; const stamped=applyNoSourceInvariantToMonthCell({...ex,state:cc.state,state_reason:cc.reason}); let netBucket:null|'+Net'|'0Net'=null; if(stamped.state==='unpaid'){ const np=netPremiumForServiceMonth(rs as any,m,{batchMonthByBatchId,...(mode==='current'?{pickerEdeByMonth:pm}:{})} as any); netBucket=np===null?'0Net':np>0?'+Net':'0Net'; } if(mode==='current' && stamped.state==='unpaid' && (stamped.carrier_recognition_premium??0)>0 && netBucket!=='+Net') netBucket='+Net'; cells[m]={...stamped,netBucket}; if(cells[m].state==='paid'){months_paid++;months_due++;} else if(cells[m].state==='unpaid'){months_unpaid++;months_due++;} else if(cells[m].state==='pending'||cells[m].state==='manual_review'){months_due++;} } const vals=Object.values(cells) as any[]; return {...row,cells,rollup:cl.rollup,needs_manual_review:cl.needs_manual_review,months_paid,months_unpaid,months_due,hasUnpaidPlusNet:vals.some(c=>c.state==='unpaid'&&c.netBucket==='+Net'),hasUnpaidZeroNet:vals.some(c=>c.state==='unpaid'&&c.netBucket==='0Net')}; });
  const flat:any[]=[]; for(const row of rows) for(const m of monthList) flat.push({row,month:m,cell:row.cells[m]}); return {records:recs,pred,rawBy,pickerMaps,rows,flat,byMember:by};
}

function hasAorBucketOnly(rs:any[], month:string){ return rs.some(r=>{ if(!isCoverallAORByName(r.aor_bucket)||isCoverallAORByName(cp(r))||isCoverallAORByName(bn(r))) return false; if(r.source_type==='EDE'){ const eff=ym(r.effective_date); return isEDEQualified(r)&&eff&&eff<=month; } if(r.source_type==='BACK_OFFICE'){ const b=getStatementMonthBounds(month); return isActiveBackOfficeRecord(r,b.start,b.end); } return false; }); }
function flagReason(rs:any[], month:string, flag:string){ if(flag==='in_ede'){ const picked=pickEdeForServiceMonth(rs.filter(r=>r.source_type==='EDE'&&isEDEQualified(r)), month); if(picked&&!isCoverallAORByName(cp(picked))) return 'month-picker-identity-fail'; if(!picked) return 'qualified-EDE-no-longer-qualifies'; return 'term-window-excludes-month'; } const b=getStatementMonthBounds(month); for(const r of rs.filter(r=>r.source_type==='BACK_OFFICE')){ const info=(NPN_MAP as any)[String(r.agent_npn??'').trim()]; if(isCoverallAORByName(bn(r))&&!info) return 'NPN-not-in-NPN_MAP'; if(String(r.eligible_for_commission??'').trim().toLowerCase()!=='yes') return 'eligibility-flag-false'; if(r.broker_term_date&&String(r.broker_term_date).substring(0,10)<=b.start) return 'broker-term-before-month'; if(r.broker_effective_date&&String(r.broker_effective_date).substring(0,10)>b.end) return 'BED-future'; } return 'off-scope-BO'; }

function currentMceCandidates(breakdown:any, selected:any[], month:string, scope:Scope, pred:(r:any)=>boolean){ const by=group(selected); const recsFor=(mk:string)=>(by.get(mk)||[]).filter(pred); const promoted=breakdown.paidRows.filter((r:any)=>!paidForServiceMonth(recsFor(r.member_key),month,{targetPayEntity:scope}).paid); const initial=[...breakdown.unpaidRows,...promoted]; const filtered=initial.filter((r:any)=>{ const rs=recsFor(r.member_key); const fe=computeFirstEligibleMonth(rs); if(fe&&fe>month) return false; if(paidForServiceMonth(rs,month,{targetPayEntity:scope}).paid) return false; try{ if(classifyMemberForMonth(rs,month)==='manual_review') return false; }catch{} return true; }); const mb=getStatementMonthBounds(month); const bo=(breakdown.universe.boActiveNonCurrentEde??[]).filter((r:any)=>{ const rs=recsFor(r.member_key); if(!rs.filter((x:any)=>x.source_type==='BACK_OFFICE').some((br:any)=>isActiveBackOfficeRecord(br,mb.start,mb.end))) return false; if(r.eligible_for_commission!=='Yes') return false; const fe=computeFirstEligibleMonth(rs); if(fe&&fe>month) return false; if(paidForServiceMonth(rs,month,{targetPayEntity:scope}).paid) return false; return true; }); return [...filtered,...bo]; }
async function mceSlice(batch:any, scope:Scope, resolverIndex:any){ const month=String(batch.statement_month).substring(0,7); const selected=await getNormalizedRecords(batch.id); const reconciled=await getReconciledMembers(batch.id); const bo=selected.filter((r:any)=>r.source_type==='BACK_OFFICE'); const adj=applyRuntimeBOActive(reconciled,bo,getStatementMonthBounds(month)); const filtered=computeFilteredEde(selected,adj.adjustedReconciled,scope,getCoveredMonths(batch.statement_month),resolverIndex); const filtered2={...filtered, uniqueMembers:filtered.uniqueMembers.filter((m:any)=>!adj.mceExclusionMemberKeys.has(m.member_key)), missingFromBO:filtered.missingFromBO.filter((m:any)=>!adj.mceExclusionMemberKeys.has(m.member_key))}; const recForBreak=adj.adjustedReconciled.filter((r:any)=>!adj.mceExclusionMemberKeys.has(r.member_key)); const breakdown=getExpectedPaymentBreakdown(recForBreak,scope,filtered2,new Set()); const cur=currentMceCandidates(breakdown,selected,month,scope,buildIsDueEligibleRecord({aorScope:'official',payEntity:scope})); const old=currentMceCandidates(breakdown,selected,month,scope,legacyPred(scope)); const curKeys=new Set(cur.map((r:any)=>r.member_key)); const removed=old.filter((r:any)=>!curKeys.has(r.member_key)); return {month,scope,current_count:cur.length,legacy_count:old.length,removed_by_v8_count:removed.length,removed_samples:sample(removed,5).map((r:any)=>({member_key:r.member_key,name:r.applicant_name,policy_number:r.policy_number}))}; }
async function bedPedCount(targetBatches:any[]){ let count=0; const samples:any[]=[]; for(const b of targetBatches){ for(const r of await getNormalizedRecords(b.id)){ if(r.source_type!=='BACK_OFFICE') continue; const bed=String(r.broker_effective_date??'').substring(0,10), ped=String(r.effective_date??'').substring(0,10); if(bed&&ped&&bed!==ped){ count++; if(samples.length<5) samples.push(compactRow(r)); } } } return {count,samples}; }

await mkdir(OUT_DIR,{recursive:true});
const batches=await getBatches(); const targetBatches=batches.filter((b:any)=>fam(b.carrier??'Ambetter')==='Ambetter'&&months.includes(String(b.statement_month).substring(0,7))).sort((a:any,b:any)=>String(a.statement_month).localeCompare(String(b.statement_month)));
const batchMonthByBatchId=new Map<string,string>(); for(const b of batches) if(b?.id&&b?.statement_month) batchMonthByBatchId.set(String(b.id),String(b.statement_month).substring(0,7));
const freshness=targetBatches.map((b:any)=>({id:b.id,statement_month:b.statement_month,carrier:b.carrier,last_full_rebuild_at:b.last_full_rebuild_at,last_rebuild_logic_version:b.last_rebuild_logic_version,fresh:new Date(b.last_full_rebuild_at).getTime()>new Date(V8_TIME).getTime()}));
const resolverIndex=await loadResolverIndex(true); const allRaw=await getAllNormalizedRecordsForMemberTimeline(); const targetIds=new Set(targetBatches.map((b:any)=>b.id)); const source=allRaw.filter((r:any)=>targetIds.has(r.batch_id)&&fam(r)==='Ambetter'); const monthList=buildMonthList('2026-01','2026-04');
const cur=buildScreen(source,resolverIndex,'Coverall','current',monthList,batchMonthByBatchId); const old=buildScreen(source,resolverIndex,'Coverall','legacy',monthList,batchMonthByBatchId); const vix=buildScreen(source,resolverIndex,'Vix','current',monthList,batchMonthByBatchId);
const cm=new Map(cur.flat.map((x:any)=>[key(x.row.member_key,x.month),x])); const om=new Map(old.flat.map((x:any)=>[key(x.row.member_key,x.month),x])); const keys=new Set([...cm.keys(),...om.keys()]);
const stateFlips:any[]=[], sourceFlips:any[]=[], optionFlips:any[]=[]; for(const k of keys){ const c:any=cm.get(k), o:any=om.get(k); const parts=String(k).split('|'); const mk=parts[0], month=parts[1]; const cc=c?.cell??{}, oc=o?.cell??{}; const rs=cur.rawBy.get(mk)||[]; if((cc.state??null)!==(oc.state??null)){ let reason='uncategorized'; if(cc.carrier_recognition) reason='D_carrier-recognition'; else if(hasAorBucketOnly(rs,month)) reason='B_aor_bucket-leakage'; else { const picked=pickEdeForServiceMonth(rs.filter((r:any)=>r.source_type==='EDE'&&isEDEQualified(r)),month); if(picked&&!isCoverallAORByName(cp(picked))) reason='E_Anna-shape-historical-EDE-span'; else if(oc.in_ede&&!cc.in_ede) reason='C_cancelled-or-unqualified-EDE'; else if((oc.in_back_office||oc.in_ede)&&!cc.due) reason='A_stale-BO'; } stateFlips.push({member_key:mk,service_month:month,old_state:oc.state??null,current_state:cc.state??null,reason,current:compactCell(c?.row,month),legacy:compactCell(o?.row,month)}); } for(const flag of ['in_ede','in_back_office']) if(!!oc[flag]!==!!cc[flag]) sourceFlips.push({member_key:mk,service_month:month,flag,old:!!oc[flag],current:!!cc[flag],reason:flagReason(rs,month,flag),current:compactCell(c?.row,month),legacy:compactCell(o?.row,month)}); if(!!cc.carrier_recognition!==!!oc.carrier_recognition) sourceFlips.push({member_key:mk,service_month:month,flag:'carrier_recognition',old:false,current:!!cc.carrier_recognition,reason:'carrier-recognition',current:compactCell(c?.row,month),legacy:compactCell(o?.row,month)}); if(cc.state==='unpaid'&&cc.carrier_recognition&&(cc.carrier_recognition_premium??0)>0&&cc.netBucket==='+Net'&&oc.netBucket!=='+Net') optionFlips.push({member_key:mk,service_month:month,current:compactCell(c?.row,month),legacy:compactCell(o?.row,month)}); }
const cr=cur.flat.filter((x:any)=>x.cell.carrier_recognition); const crPos=cr.filter((x:any)=>x.cell.state==='unpaid'&&(x.cell.carrier_recognition_premium??0)>0); const crPlus=crPos.filter((x:any)=>x.cell.netBucket==='+Net');
const crSamples=sample(cr,5).map((x:any)=>{ const rs=cur.rawBy.get(x.row.member_key)||[]; const b=getStatementMonthBounds(x.month); const bo=rs.find((r:any)=>r.source_type==='BACK_OFFICE'&&isCoverallAORByName(bn(r))&&(NPN_MAP as any)[String(r.agent_npn??'').trim()]&&isActiveBackOfficeRecord(r,b.start,b.end)); const picked=cur.pickerMaps.get(x.row.member_key)?.get(x.month); return {cell:compactCell(x.row,x.month),bo:compactRow(bo),picked_ede:compactRow(picked)}; });
const vixGate=vix.flat.filter((x:any)=>{ const rs=vix.rawBy.get(x.row.member_key)||[]; const b=getStatementMonthBounds(x.month); const bo=rs.find((r:any)=>{ const info=(NPN_MAP as any)[String(r.agent_npn??'').trim()]; return r.source_type==='BACK_OFFICE'&&isCoverallAORByName(bn(r))&&info?.expectedPayEntity==='Coverall'&&isActiveBackOfficeRecord(r,b.start,b.end); }); const picked=vix.pickerMaps.get(x.row.member_key)?.get(x.month); return bo&&picked&&!isCoverallAORByName(cp(picked)); });
function anna(kind:'a'|'b'){ for(const x of cur.flat.filter((z:any)=>z.month==='2026-02')){ const rs=cur.rawBy.get(x.row.member_key)||[]; const jan=rs.find((r:any)=>r.source_type==='EDE'&&ym(r.effective_date)<='2026-01'&&isCoverallAORByName(cp(r))&&isEDEQualified(r)); const picked=cur.pickerMaps.get(x.row.member_key)?.get('2026-02'); if(!jan||!picked||isCoverallAORByName(cp(picked))) continue; const b=getStatementMonthBounds('2026-02'); const activeBo=rs.find((r:any)=>r.source_type==='BACK_OFFICE'&&isCoverallAORByName(bn(r))&&(NPN_MAP as any)[String(r.agent_npn??'').trim()]&&isActiveBackOfficeRecord(r,b.start,b.end)); const cell=x.row.cells['2026-02']; if(kind==='a'&&activeBo&&cell.in_back_office&&!cell.in_ede&&cell.carrier_recognition) return {current:compactCell(x.row,'2026-02'),jan_coverall_ede:compactRow(jan),feb_picked_ede:compactRow(picked),active_bo:compactRow(activeBo),hasUnpaidPlusNet:!!x.row.hasUnpaidPlusNet}; const off=rs.find((r:any)=>r.source_type==='BACK_OFFICE'&&(!isCoverallAORByName(bn(r))||!(NPN_MAP as any)[String(r.agent_npn??'').trim()])); if(kind==='b'&&off&&!cell.in_back_office&&!cell.in_ede&&!cell.carrier_recognition&&cell.state==='not_expected_cancelled'&&!cell.due) return {current:compactCell(x.row,'2026-02'),jan_coverall_ede:compactRow(jan),feb_picked_ede:compactRow(picked),off_scope_bo:compactRow(off),appearsInDueRows:x.row.months_due>0}; } return null; }
const inv={unmapped_bo:[] as any[],aor_bucket_only:[] as any[],picker_mismatch:[] as any[],cr_bad:[] as any[]}; for(const x of cur.flat){ const rs=cur.rawBy.get(x.row.member_key)||[]; const b=getStatementMonthBounds(x.month); if(x.cell.in_back_office){ const bad=rs.find((r:any)=>r.source_type==='BACK_OFFICE'&&isCoverallAORByName(bn(r))&&!(NPN_MAP as any)[String(r.agent_npn??'').trim()]&&isActiveBackOfficeRecord(r,b.start,b.end)); if(bad) inv.unmapped_bo.push({cell:compactCell(x.row,x.month),record:compactRow(bad)}); } if((x.cell.in_ede||x.cell.in_back_office)&&hasAorBucketOnly(rs,x.month)){ const support=rs.some((r:any)=>(r.source_type==='EDE'&&x.cell.in_ede&&isCoverallAORByName(cp(r)))||(r.source_type==='BACK_OFFICE'&&x.cell.in_back_office&&isCoverallAORByName(bn(r))&&(NPN_MAP as any)[String(r.agent_npn??'').trim()])); if(!support) inv.aor_bucket_only.push({cell:compactCell(x.row,x.month)}); } if(x.cell.in_ede){ const picked=cur.pickerMaps.get(x.row.member_key)?.get(x.month); if(!picked||!isCoverallAORByName(cp(picked))) inv.picker_mismatch.push({cell:compactCell(x.row,x.month),picked:compactRow(picked)}); } if(x.cell.carrier_recognition){ const bo=rs.find((r:any)=>r.source_type==='BACK_OFFICE'&&isCoverallAORByName(bn(r))&&(NPN_MAP as any)[String(r.agent_npn??'').trim()]&&isActiveBackOfficeRecord(r,b.start,b.end)); const picked=cur.pickerMaps.get(x.row.member_key)?.get(x.month); if(!bo||!picked||isCoverallAORByName(cp(picked))) inv.cr_bad.push({cell:compactCell(x.row,x.month),bo:compactRow(bo),picked:compactRow(picked)}); } }
const mce:any={}; const bedped=await bedPedCount(targetBatches);
const analysis={generated_at:new Date().toISOString(),v8_commit_time:V8_TIME,freshness,freshness_pass:freshness.length===4&&freshness.every((f:any)=>f.fresh),record_counts:{target_batches:targetBatches.length,all_mt_records_raw:allRaw.length,target_mt_records:source.length,coverall_current_rows:cur.rows.length,coverall_current_due_rows:cur.rows.filter((r:any)=>r.months_due>0).length,coverall_legacy_rows:old.rows.length},state_transition_matrix:{total_flips:stateFlips.length,by_reason:counts(stateFlips,'reason'),uncategorized_count:stateFlips.filter(r=>r.reason==='uncategorized').length,samples:sample(stateFlips,10)},source_flag_deltas:{total_flips:sourceFlips.length,by_flag:counts(sourceFlips,'flag'),by_reason:counts(sourceFlips,'reason'),uncategorized_count:sourceFlips.filter(r=>String(r.reason).includes('uncategorized')).length,samples:sample(sourceFlips,10)},carrier_recognition:{count:cr.length,positive_unpaid_count:crPos.length,positive_unpaid_plus_net_count:crPlus.length,samples:crSamples,vix_pay_entity_gate_candidate_count:vixGate.length,vix_pay_entity_gate_samples:sample(vixGate,5).map((x:any)=>({current:compactCell(x.row,x.month),carrier_recognition_is_undefined:!x.cell.carrier_recognition}))},optionA:{expected_positive_unpaid_cr_count:crPos.length,actual_positive_unpaid_cr_plus_net_count:crPlus.length,legacy_to_current_plus_net_flip_count:optionFlips.length,samples:sample(optionFlips,5)},anna:{variant_a:anna('a'),variant_b:anna('b')},invariants:{sliceA_unmapped_coverall_bo_in_back_office:{count:inv.unmapped_bo.length,samples:sample(inv.unmapped_bo,5)},sliceA_aor_bucket_only_source_flags:{count:inv.aor_bucket_only.length,samples:sample(inv.aor_bucket_only,5)},sliceD_in_ede_picker_mismatch:{count:inv.picker_mismatch.length,samples:sample(inv.picker_mismatch,5)},sliceC_cr_without_required_evidence:{count:inv.cr_bad.length,samples:sample(inv.cr_bad,5)}},mce:{slices:mce,mce_bed_ped_row_count:bedped.count,mce_bed_ped_samples:bedped.samples},similar_blind_spots:{dashboard_premium_split_divergence_prior:126,dashboard_premium_split_divergence_current:126,mce_bed_ped_prior:8792,mce_bed_ped_current:bedped.count,cr_layer2_filter_scan:'grep separately: no new carrier-recognition top-level filter/bucket/pill found'}};
await writeFile(OUT_DIR+'/analysis.json',JSON.stringify(analysis,null,2)); await writeFile(OUT_DIR+'/carrier-recognition-samples.json',JSON.stringify(crSamples,null,2)); await writeFile(OUT_DIR+'/state-flip-samples.json',JSON.stringify(sample(stateFlips,50),null,2)); await writeFile(OUT_DIR+'/source-flag-flip-samples.json',JSON.stringify(sample(sourceFlips,50),null,2));
console.log(JSON.stringify({freshness_pass:analysis.freshness_pass,record_counts:analysis.record_counts,state_transition_matrix:analysis.state_transition_matrix,source_flag_deltas:analysis.source_flag_deltas,carrier_recognition:{count:cr.length,positive_unpaid_count:crPos.length,positive_unpaid_plus_net_count:crPlus.length,vix_pay_entity_gate_candidate_count:vixGate.length},optionA:analysis.optionA,anna:analysis.anna,invariants:Object.fromEntries(Object.entries(analysis.invariants).map(([k,v]:any)=>[k,v.count])),mce_counts:Object.fromEntries(Object.entries(mce).map(([k,v]:any)=>[k,{current_count:v.current_count,legacy_count:v.legacy_count,removed_by_v8_count:v.removed_by_v8_count}])),blind_spots:analysis.similar_blind_spots},null,2));
